
//*! AQUI CREAMOS LA INTERFAZ Y LE DEFINIMOS LOS DATOS QUE TENDRA Y DE QUE TIPO SERAN, UNA VEZ CREADA YA PODREMOS DEFINIR EN EL ARREGLO QUE ES DEL TIPO CHARACTER, QUE ES LO QUE ESTAMOS CREANDO AQUI.
export interface Character {
  name: string;
  power: number;


}
